### ISSUE TITLE
Mod deployment to %UserProfile%\Documents\My Games\Starfield

### ISSUE THREAD

**Issue by fre-sch** [Nexus-Mods/game-starfield#26] opened 2023-11-05 19:05 UTC
Please make mod deployment to `%UserProfile%\Documents\My Games\Starfield` an optional strategy. Clearly this was added intentionally by Bethesda as a more isolated option to the main installation directory, where mixing vanilla files and mod files would quickly create unwieldly messes.

Judging by the explanations (in Vortex, at [modding.wiki](https://modding.wiki/en/vortex/users/starfield-folder-junction-issues.
)) a OneDrive managed `%UserProfile%\Documents` directory can lead to issues. However, I would argue, as is evident by the detailed wiki article, using workarounds, using folder junctions as means of "removing" `%UserProfile%\Documents\My Games\Starfield` is potentially more problematic than just using `%UserProfile%\Documents\My Games\Starfield` as intended: by placing downloaded mod files there.

Surely with the same amount of time and care spent on making the workarounds and explanation of workarounds, `%UserProfile%\Documents\My Games\Starfield` could be offered as legitimate deployment target of Vortex downloaded mods. For users without OneDrive managed `%UserProfile%\Documents` this offers a substantially better experience as any of these workarounds (_just to have the game installation directory as sole Vortex mod deployment target_).

Having said all this, I'm aware of how `%UserProfile%\Documents\My Games\Starfield` is not a valid target for SFSE and its plugins. But I would rather argue SFSE and its plugins are the current special case since Starfield itself has no (sensible) plugins.txt loading alternative, with `sTestFile` being collectively regarded as _Bad Idea_. Once Bethesda enables their own version of plugins.txt, this becomes a moot point however. In that case using SFSE and PluginsTXTEnabler will become a source of problems demonstrating the problems of mixing mod-files with vanilla files, requiring some form of cleanup.

**Comment by Pickysaurus** [comment] 2023-11-05 20:22
Duplicate of https://github.com/Nexus-Mods/game-starfield/issues/2

**Closed as completed by Pickysaurus** 2023-11-05 20:22 UTC
